jobs:
  include:
    - language: go
      go: "1.10"
      install: skip
      before_script: cd impl/go
      script: go test

    - language: java
      jdk: openjdk11
      install: skip
      before_script: cd impl/java
      script: mvn test

    - language: node_js
      node_js: 12
      install: skip
      before_script: cd impl/js
      script: npm test

    - language: python
      python: 3.4
      install: skip
      before_script: cd impl/python
      script: python3 -m pytest

    - language: ruby
      rvm: 2.0
      install: skip
      before_script: cd impl/ruby
      script: ruby lib/any_ascii_test.rb

    - language: rust
      rust: "1.42.0"
      install: skip
      before_script: cd impl/rust
      script: cargo test

    - language: csharp
      mono: none
      dotnet: "3.0.103"
      solution: csharp/AnyAscii.sln
      install: skip
      before_script: cd impl/csharp
      script: dotnet test

    - language: sh
      install: skip
      before_script: cd impl/sh
      script: ./test.sh

    - language: php
      php: '5.6'
      install: skip
      before_script: cd impl/php
      script: php test.php

    - language: julia
      julia: 1.0
      install: skip
      before_script: cd impl/julia
      script: julia --project=. -e 'using Pkg; Pkg.test()'

    - language: c
      install: skip
      before_script: cd impl/c
      script: ./test.sh

    - language: elixir
      elixir: '1.12.3'
      otp_release: '22'
      install: skip
      before_script: cd impl/elixir
      script: mix test
